package io.quarkus.bootstrap.runtime;

import java.util.Objects;

/**
 * Provides a low-level API for registering and accessing runtime values generated by Quarkus or Quarkus
 * extensions. Typically, such values describe a fully configured application, known only at application startup,
 * such as the HTTP port.
 * <p>
 * These values should not be exposed by the Config mechanism directly, as that would require mutating the Config
 * system, which should be immutable, and cause hard-to-debug issues. Instead, {@code QuarkusRuntime} should be
 * preferred for exposing such values.
 */
public interface QuarkusRuntime {
    /**
     * Registers a value with a specified key.
     *
     * @param key key with which the specified value is to be associated
     * @param value value to be associated with the specified key
     * @throws IllegalArgumentException if the specified key already has an associated value
     */
    <T> void register(final RuntimeKey<T> key, final T value);

    /**
     * Registers a {@link Info} with a specified key.
     *
     * @param key key with which the specified value is to be associated
     * @param info value to be associated with the specified key
     * @throws IllegalArgumentException if the specified key already has an associated value
     * @see QuarkusRuntime.Info
     */
    <T> void registerInfo(final RuntimeKey<T> key, final Info<T> info);

    /**
     * Returns the value to which the specified key is mapped.
     *
     * @param key the key whose associated value is to be returned
     * @return the value to which the specified key is mapped
     * @throws java.lang.IllegalArgumentException if the specified key has no associated value
     */
    <T> T get(final RuntimeKey<T> key);

    /**
     * Returns the value to which the specified key is mapped.
     *
     * @param key the key whose associated value is to be returned
     * @param defaultValue the default mapping of the key
     * @return the value to which the specified key is mapped, or {@code defaultValue} if the key has no value
     */
    <T> T getOrDefault(final RuntimeKey<T> key, final T defaultValue);

    /**
     * Returns {@code true} if {@link QuarkusRuntime} contains a mapping for the specified key.
     *
     * @param key key whose presence in {@link QuarkusRuntime} is to be tested
     * @return {@code true} if {@link QuarkusRuntime} contains a mapping for the specified key
     */
    <T> boolean containsKey(final RuntimeKey<T> key);

    /**
     * Allows to defer and retrieve instances of an object that represent information only available at
     * runtime with {@link QuarkusRuntime}.
     */
    interface Info<T> {
        /**
         * Construct a new instance of {@code T}.
         *
         * @param quarkusRuntime which carries information to construct a new instance of {@code T}.
         * @return an instance of {@code T}.
         */
        T get(QuarkusRuntime quarkusRuntime);

        class SimpleInfo<T> implements Info<T> {
            private final T value;

            SimpleInfo(T value) {
                this.value = value;
            }

            @Override
            public T get(QuarkusRuntime quarkusRuntime) {
                return value;
            }

            public static <T> SimpleInfo<T> of(final T value) {
                return new SimpleInfo<>(value);
            }
        }
    }

    /**
     * A typed key.
     */
    final class RuntimeKey<T> {
        private final String key;

        RuntimeKey(String key) {
            this.key = key;
        }

        public String key() {
            return key;
        }

        @Override
        public boolean equals(Object o) {
            if (!(o instanceof RuntimeKey<?> that))
                return false;
            return Objects.equals(key, that.key);
        }

        @Override
        public int hashCode() {
            return Objects.hashCode(key);
        }

        public static <T> RuntimeKey<T> key(final String key) {
            return new RuntimeKey<>(key);
        }

        public static <T> RuntimeKey<T> key(final Class<T> type) {
            return new RuntimeKey<>(type.getName());
        }

        public static RuntimeKey<Integer> intKey(final String key) {
            return new RuntimeKey<>(key);
        }

        // TODO - Add static constructors as needed
    }

    // TODO - Add javadoc - Used for Config
    @Deprecated(forRemoval = true)
    Info<?> get(final String key);
}
